### ISSUE TITLE
WebSSO Login

### ISSUE THREAD

**Issue by b1n4ryj4n** [rockihack/Stud.IP-FileSync#11]
Hey,
can u add a option to login via WebSSO?

Because i get always multiple errors with:
"Upps, da ist etwas schief gelaufen."

**Comment by b1n4ryj4n** [comment]
Can't copy the error details, it pops up so many times. (https://www.youtube.com/watch?v=EbBUZvqX9Lo)
I use Java 10 SE because Java SE 9 has reached end of support.

**Comment by rockihack** [comment]
Is Java 10 the only installed Java Version?
It seems that FileSync is executed with Java 8.

Open a command prompt and verify it with: `java -version`
Then try to run it with: `java -jar filesync.jar`

**Comment by b1n4ryj4n** [comment]
java --version
```
java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```
But i started it now with  C:\Program Files\Java\jre-10.0.1\bin\java.exe -jar B:\filesync.jar
and it works (login with websso too), only the progress spinner is now smaller than usually.
https://imgur.com/SPRFHmA

**Comment by rockihack** [comment]
Ok, thats a known issue with Java 10.
